DROP TABLE IF EXISTS T_ASSET CASCADE;
DROP TABLE IF EXISTS T_ASSETTYPE CASCADE;
DROP TABLE IF EXISTS T_PROTOCOL CASCADE;
DROP TABLE IF EXISTS T_MANUFACTURER CASCADE;
DROP TABLE IF EXISTS T_USER CASCADE;
DROP TABLE IF EXISTS T_PROJECTGROUP CASCADE;
DROP TABLE IF EXISTS T_SUBSCRIPTION CASCADE;
DROP TABLE IF EXISTS T_ROLE CASCADE;
DROP TABLE IF EXISTS T_LOG CASCADE;
DROP TABLE IF EXISTS T_TOKEN CASCADE;


CREATE TABLE T_ASSET (
   ID                   VARCHAR(8)           NOT NULL,
   ASSET_ID              VARCHAR(32)          NULL,
   ASSET_NAME                 VARCHAR(32)          NOT NULL,
   ASSET_MODEL                VARCHAR(32)          NOT NULL,
   ASSET_TYPE_ID                 VARCHAR(32)          NOT NULL,
   ASSET_PROTOCOL_ID				VARCHAR(32)			 NOT NULL,
   ASSET_STATUS               VARCHAR(8)           NULL,
   ASSET_MANUFACTURER_ID         VARCHAR(32)          NOT NULL,
   ASSET_DESCRIPTION          VARCHAR(256)         NULL,
   CONSTRAINT PK_T_ASSET PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_ASSET_PK ON T_ASSET (ID);

CREATE TABLE T_ASSETTYPE (
   ID                   VARCHAR(8)           NOT NULL,
   TYPE_NAME                 VARCHAR(32)          NOT NULL,
   TYPE_DESCRIPTION          VARCHAR(256)         NULL,
   CONSTRAINT PK_T_ASSETTYPE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_ASSETTYPE_PK ON T_ASSETTYPE (ID);

CREATE TABLE T_MANUFACTURER (
	ID VARCHAR(32)	NOT NULL,
	MANUFACTURER_NAME	VARCHAR(32) NOT NULL,
	MANUFACTURER_DESCRIPTION	VARCHAR(256),
	CONSTRAINT PK_T_MANUFACTURER PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_MANUFACTURER_PK ON T_MANUFACTURER(ID);

CREATE TABLE T_PROTOCOL (
	ID	VARCHAR(32) NOT NULL,
	PROTOCOL_NAME	VARCHAR(32) NOT NULL,
	PROTOCOL_DESCRIPTION VARCHAR(256)	NULL,
	CONSTRAINT PK_T_PROTOCOL PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_PROTOCOL_PK ON T_PROTOCOL(ID);

CREATE TABLE T_USER (
	ID					VARCHAR(8)			NOT NULL,
   USER_ID                   VARCHAR(8)           NOT NULL,
   USER_NAME                 VARCHAR(32)          NOT NULL,
   USER_PASSWORD				VARCHAR(256)		 NOT NULL,
   USER_EMAIL                VARCHAR(64)          NOT NULL,
   USER_PROJECTGROUP_ID         VARCHAR(32)          NOT NULL,
   USER_ROLE_ID                VARCHAR(16)          NOT NULL,
   CONSTRAINT PK_T_USER PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_USER_PK ON T_USER (ID);

CREATE TABLE T_PROJECTGROUP (
	ID	VARCHAR(32) NOT NULL,
	PROJECTGROUP_NAME	VARCHAR(32) NOT NULL,
	PROJECTGROUP_DESCRIPTION VARCHAR(256),
	CONSTRAINT PK_T_PROJECTGROUP PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_PROJECTGROUP_PK ON T_PROJECTGROUP(ID);

CREATE TABLE T_SUBSCRIPTION (
   ID    VARCHAR(8)  NOT NULL,
   ASSET_ID   VARCHAR(8)  NOT NULL,
   USER_ID   VARCHAR(8)  NOT NULL,
   SUBSCRIPTION_TIME  TIMESTAMP NOT NULL,
   CONSTRAINT PK_T_SUBSCRIPTION PRIMARY KEY (ID)
);
CREATE INDEX T_SUBSCRIPTION_PK ON T_SUBSCRIPTION(ID);

CREATE TABLE T_LOG (
   ID                   VARCHAR(8)           NOT NULL,
   DATE                 TIMESTAMP            NULL,
   OPERATOR             VARCHAR(32)          NULL,
   LOG_CONTENT              VARCHAR(256)         NULL,
   CONSTRAINT PK_T_LOG PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_LOG_PK ON T_LOG (ID);

CREATE TABLE T_ROLE (
   ID                   VARCHAR(8)           NOT NULL,
   ROLE_NAME                 VARCHAR(32)          NOT NULL,
   ROLE_DESCRIPTION          VARCHAR(256)         NULL,
   CONSTRAINT PK_T_ROLE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_ROLE_PK ON T_ROLE (ID);

CREATE TABLE T_TOKEN (
   ID                   VARCHAR(8)           NOT NULL,
   CONSTRAINT PK_T_TOKEN PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX T_TOKEN_PK ON T_TOKEN (ID);




