banner:
    charset: UTF-8
spring:
    application:
        name: Asset Management Platform

    datasource:
        name: asset
        url: jdbc:postgresql://localhost/asset
        username: asset
        password: asset
        driverClassName: org.postgresql.Driver
        max-active: 100
        max-idle: 8
        min-idle: 8

    dao:
        exceptiontranslation:
            enabled: true

    jpa:
        database: postgresql
        show-sql: true
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update

    mail:
        host: smtp.163.com
        port: 25
        protocol: smtp
        username:
        password:
        default-encoding: UTF-8

#security:
#    user: admin
#    password: admin
#    role: SUPERUSER

logging:
    level.*: DEBUG  #(TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
    #file: run.log
    #path: /var/log