banner:
    charset: UTF-8

server:
    address: 127.0.0.1
    port: 8080
    session:
        timeout: 180
#    ssl:
#      key-store:
#      key-store-password:
    compression:
      enabled: true
      mime-types: `text/html,text/css,application/json`

spring:

    aop:
          auto: true
          proxy-target-class: false

    application:
        name: Asset Management Platform

    datasource:
        name: asset
        url: jdbc:postgresql://localhost/asset
        username: asset
        password: asset
        driverClassName: org.postgresql.Driver
        max-active: 100
        max-idle: 8
        min-idle: 8

    dao:
        exceptiontranslation:
            enabled: true

    jpa:
        database: postgresql
        show-sql: true
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update

    mail:
        host: smtp.163.com
        port: 25
        protocol: smtp
        username:
        password:
        default-encoding: UTF-8

    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

    mvc:
      favicon:
        enabled: true
#security:
#    user: admin
#    password: admin
#    role: SUPERUSER

logging:
    config: `classpath:logback-spring.xml`
    level.*: DEBUG  #(TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
    #file: run.log

