spring:
    profiles: development
server:
    address: 127.0.0.1
    port: 8080
security:
    user: admin
    password: admin


spring:
    profiles: production
server:
    address: 127.0.0.1
    port: 8080
security:
    user: admin
    password: admin